\c fce;
-- trainers sample data
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Gale','McKiddin','gmckiddin0@opensource.org','607-633-8221',false,false,true,true,false);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Arleta','Tabbitt','atabbitt1@europa.eu','222-933-8902',true,false,true,false,true);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Lura','Steinor','lsteinor2@opensource.org','125-933-3792',false,true,true,false,false);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Nolie','Vahey','nvahey3@who.int','455-478-9608',true,true,true,false,true);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Bertrand','Staddom','bstaddom4@mozilla.com','937-153-9556',true,false,true,true,true);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Johnathan','Rolfe','jrolfe5@chronoengine.com','216-595-9101',true,true,false,false,false);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Birk','Curryer','bcurryer6@blogspot.com','654-358-2220',true,true,true,true,true);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Gloria','Wroe','gwroe7@google.ru','176-817-6255',false,false,false,true,true);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Sawyere','Gaitone','sgaitone8@acquirethisname.com','856-385-6410',true,true,true,true,false);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Howard','Spikings','hspikings9@edublogs.org','124-230-0236',true,false,false,false,false);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Jed','Helgass','jhelgassa@mayoclinic.com','777-319-4993',false,true,true,false,true);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Cyndi','Letts','clettsb@google.com.hk','903-828-0400',false,false,false,true,false);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Bunni','Hinkens','bhinkensc@ft.com','829-992-1307',false,true,true,true,false);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Edlin','Elfitt','eelfittd@sfgate.com','527-397-0551',true,true,true,false,true);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Alexandr','Heinrich','aheinriche@gravatar.com','342-848-9603',true,false,false,false,false);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Raimund','holmes','rholmesf@phpbb.com','690-598-4604',false,true,true,false,false);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Binky','Seal','bsealg@wikimedia.org','370-383-1232',true,true,true,false,false);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Katerine','Odde','koddeh@sun.com','670-386-0292',true,true,false,true,true);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Major','Wooland','mwoolandi@amazonaws.com','924-600-0565',false,false,false,true,false);
insert into trainers (picture, first_name, last_name, email, phone_number, bodybuilding, running, power_lifting, swimming, cycling) values ('','Noellyn','Ledeker','nledekerj@printfriendly.com','390-327-3553',true,true,false,false,true);

-- comments sample data
insert into comments (comment_body, trainer_id) values ('rutrum at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum', 1);
insert into comments (comment_body, trainer_id) values ('consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut', 1);
insert into comments (comment_body, trainer_id) values ('eget semper rutrum nulla nunc purus phasellus in felis donec', 1);
insert into comments (comment_body, trainer_id) values ('justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 1);
insert into comments (comment_body, trainer_id) values ('dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero', 1);
insert into comments (comment_body, trainer_id) values ('magnis dis parturient montes nascetur ridiculus mus etiam vel augue vestibulum rutrum', 2);
insert into comments (comment_body, trainer_id) values ('integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci', 2);
insert into comments (comment_body, trainer_id) values ('eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum', 2);
insert into comments (comment_body, trainer_id) values ('vitae nisl aenean lectus pellentesque eget nunc donec quis orci', 2);
insert into comments (comment_body, trainer_id) values ('rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta', 2);
insert into comments (comment_body, trainer_id) values ('vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 3);
insert into comments (comment_body, trainer_id) values ('ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio', 3);
insert into comments (comment_body, trainer_id) values ('duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede', 3);
insert into comments (comment_body, trainer_id) values ('vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 3);
insert into comments (comment_body, trainer_id) values ('rhoncus aliquam lacus morbi quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed', 3);
insert into comments (comment_body, trainer_id) values ('ornare consequat lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl', 4);
insert into comments (comment_body, trainer_id) values ('ultrices libero non mattis pulvinar nulla pede ullamcorper augue a', 4);
insert into comments (comment_body, trainer_id) values ('adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non', 4);
insert into comments (comment_body, trainer_id) values ('sit amet nunc viverra dapibus nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus', 4);
insert into comments (comment_body, trainer_id) values ('cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque', 4);
insert into comments (comment_body, trainer_id) values ('in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan', 5);
insert into comments (comment_body, trainer_id) values ('ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci', 5);
insert into comments (comment_body, trainer_id) values ('vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi', 5);
insert into comments (comment_body, trainer_id) values ('cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam', 5);
insert into comments (comment_body, trainer_id) values ('risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed', 5);
insert into comments (comment_body, trainer_id) values ('id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue', 6);
insert into comments (comment_body, trainer_id) values ('eleifend pede libero quis orci nullam molestie nibh in lectus', 6);
insert into comments (comment_body, trainer_id) values ('id luctus nec molestie sed justo pellentesque viverra pede ac diam cras pellentesque volutpat dui maecenas tristique est et', 6);
insert into comments (comment_body, trainer_id) values ('iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum', 6);
insert into comments (comment_body, trainer_id) values ('turpis elementum ligula vehicula consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus', 6);
insert into comments (comment_body, trainer_id) values ('lorem ipsum dolor sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non', 7);
insert into comments (comment_body, trainer_id) values ('rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede lobortis ligula sit', 7);
insert into comments (comment_body, trainer_id) values ('elit sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas', 7);
insert into comments (comment_body, trainer_id) values ('nulla elit ac nulla sed vel enim sit amet nunc viverra dapibus', 7);
insert into comments (comment_body, trainer_id) values ('dapibus duis at velit eu est congue elementum in hac habitasse platea dictumst morbi', 7);
insert into comments (comment_body, trainer_id) values ('tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum', 8);
insert into comments (comment_body, trainer_id) values ('vel est donec odio justo sollicitudin ut suscipit a feugiat', 8);
insert into comments (comment_body, trainer_id) values ('purus sit amet nulla quisque arcu libero rutrum ac lobortis vel', 8);
insert into comments (comment_body, trainer_id) values ('mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus', 8);
insert into comments (comment_body, trainer_id) values ('accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor', 8);
insert into comments (comment_body, trainer_id) values ('lacinia aenean sit amet justo morbi ut odio cras mi pede malesuada in imperdiet', 9);
insert into comments (comment_body, trainer_id) values ('eget rutrum at lorem integer tincidunt ante vel ipsum praesent', 9);
insert into comments (comment_body, trainer_id) values ('luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend', 9);
insert into comments (comment_body, trainer_id) values ('cras mi pede malesuada in imperdiet et commodo vulputate justo in', 9);
insert into comments (comment_body, trainer_id) values ('in quis justo maecenas rhoncus aliquam lacus morbi quis tortor id nulla ultrices', 9);
insert into comments (comment_body, trainer_id) values ('augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac habitasse', 10);
insert into comments (comment_body, trainer_id) values ('mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', 10);
insert into comments (comment_body, trainer_id) values ('pede justo eu massa donec dapibus duis at velit eu est congue elementum in hac habitasse platea', 10);
insert into comments (comment_body, trainer_id) values ('ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus', 10);
insert into comments (comment_body, trainer_id) values ('augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis', 10);
insert into comments (comment_body, trainer_id) values ('lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit', 11);
insert into comments (comment_body, trainer_id) values ('vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia', 11);
insert into comments (comment_body, trainer_id) values ('blandit lacinia erat vestibulum sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo', 11);
insert into comments (comment_body, trainer_id) values ('velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus', 11);
insert into comments (comment_body, trainer_id) values ('velit eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit', 11);
insert into comments (comment_body, trainer_id) values ('fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in porttitor pede justo', 12);
insert into comments (comment_body, trainer_id) values ('eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse ornare consequat lectus in est risus', 12);
insert into comments (comment_body, trainer_id) values ('adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante', 12);
insert into comments (comment_body, trainer_id) values ('venenatis non sodales sed tincidunt eu felis fusce posuere felis sed', 12);
insert into comments (comment_body, trainer_id) values ('lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus', 12);
insert into comments (comment_body, trainer_id) values ('lobortis ligula sit amet eleifend pede libero quis orci nullam', 13);
insert into comments (comment_body, trainer_id) values ('ac nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in', 13);
insert into comments (comment_body, trainer_id) values ('vestibulum velit id pretium iaculis diam erat fermentum justo nec condimentum neque sapien placerat ante nulla justo', 13);
insert into comments (comment_body, trainer_id) values ('in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices phasellus', 13);
insert into comments (comment_body, trainer_id) values ('aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra', 13);
insert into comments (comment_body, trainer_id) values ('condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', 14);
insert into comments (comment_body, trainer_id) values ('egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend', 14);
insert into comments (comment_body, trainer_id) values ('nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', 14);
insert into comments (comment_body, trainer_id) values ('morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus', 14);
insert into comments (comment_body, trainer_id) values ('duis aliquam convallis nunc proin at turpis a pede posuere nonummy integer non velit donec', 14);
insert into comments (comment_body, trainer_id) values ('aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi', 15);
insert into comments (comment_body, trainer_id) values ('velit donec diam neque vestibulum eget vulputate ut ultrices vel augue vestibulum ante ipsum primis', 15);
insert into comments (comment_body, trainer_id) values ('sed interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa', 15);
insert into comments (comment_body, trainer_id) values ('tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus', 15);
insert into comments (comment_body, trainer_id) values ('mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum', 15);
insert into comments (comment_body, trainer_id) values ('amet lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla', 16);
insert into comments (comment_body, trainer_id) values ('interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec', 16);
insert into comments (comment_body, trainer_id) values ('a ipsum integer a nibh in quis justo maecenas rhoncus aliquam lacus', 16);
insert into comments (comment_body, trainer_id) values ('nulla integer pede justo lacinia eget tincidunt eget tempus vel pede', 16);
insert into comments (comment_body, trainer_id) values ('sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis', 16);
insert into comments (comment_body, trainer_id) values ('sollicitudin ut suscipit a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique fusce congue', 17);
insert into comments (comment_body, trainer_id) values ('curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu interdum eu tincidunt in', 17);
insert into comments (comment_body, trainer_id) values ('potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet', 17);
insert into comments (comment_body, trainer_id) values ('quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus', 17);
insert into comments (comment_body, trainer_id) values ('vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget congue eget', 17);
insert into comments (comment_body, trainer_id) values ('eu est congue elementum in hac habitasse platea dictumst morbi vestibulum velit id', 18);
insert into comments (comment_body, trainer_id) values ('volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus', 18);
insert into comments (comment_body, trainer_id) values ('montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et', 18);
insert into comments (comment_body, trainer_id) values ('elementum in hac habitasse platea dictumst morbi vestibulum velit id', 18);
insert into comments (comment_body, trainer_id) values ('quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et', 18);
insert into comments (comment_body, trainer_id) values ('curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor morbi', 19);
insert into comments (comment_body, trainer_id) values ('accumsan odio curabitur convallis duis consequat dui nec nisi volutpat eleifend donec ut dolor', 19);
insert into comments (comment_body, trainer_id) values ('sed augue aliquam erat volutpat in congue etiam justo etiam pretium iaculis', 19);
insert into comments (comment_body, trainer_id) values ('nulla pede ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra', 19);
insert into comments (comment_body, trainer_id) values ('tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl', 19);
insert into comments (comment_body, trainer_id) values ('cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at', 20);
insert into comments (comment_body, trainer_id) values ('id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu', 20);
insert into comments (comment_body, trainer_id) values ('ut ultrices vel augue vestibulum ante ipsum primis in faucibus orci luctus', 20);
insert into comments (comment_body, trainer_id) values ('ut odio cras mi pede malesuada in imperdiet et commodo', 20);
insert into comments (comment_body, trainer_id) values ('est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac', 20);